from tkinter import *
raiz = Tk()
raiz.title("Ventana de pruebas")
raiz.resizable()
#raiz.geometry("650x350")
raiz.config(bg="#536")
miFrame = Frame()
miFrame.pack(fill="both",expand ="True")
#miFrame.pack(side="top",anchor="n")
miFrame.config(width="600",height="300")
miFrame.config(bg="red")
miFrame.config(bd="35")
miFrame.config(relief="groove")
miFrame.config(cursor="pirate")
raiz.mainloop()